# Generated by Django 2.2.1 on 2019-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinytoCloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedpublickey',
            name='N',
            field=models.CharField(max_length=1400),
        ),
    ]
